### ISSUE TITLE
Logout likely needed for askbot

### ISSUE THREAD

**Issue by iainbryson** [dtu-compute/dtu-enote-askbot#12]
If you're logged in to CAS with a user who doesn't have access to askbot, the click 'Sign in via DTU Campus Net', you'll just get redirected to the same page.

Probably if a user is logged in but isn't in the course it should read something like 
'User XXX logged in, but not part of the course, so read only access. Click here to logout"

**Comment by iainbryson** [comment]
I guess if we get rid of askbot this isn't an issue any more

**Comment by dtu-compute** [comment]
Yes, I am closing =)
